apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-serve-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-serve-web
  template:
    metadata:
      labels:
        app: table-serve-web
    spec:
      containers:
      - name: table-serve-web
        image: habahmed/table-serve-web:latest
        ports:
        - containerPort: 80


